/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/_app/__root'
import { Route as layoutsWorkspaceRouteImport } from './../routes/_layouts/workspace'
import { Route as layoutsLandingRouteImport } from './../routes/_layouts/landing'
import { Route as layoutsAuthRouteImport } from './../routes/_layouts/auth'
import { Route as IndexRouteImport } from './../routes/_landing/index'
import { Route as appApiDotsplatRouteImport } from './../routes/_app/api.$'
import { Route as TasksRouteImport } from './../routes/_works-pace/tasks'
import { Route as ReportsRouteImport } from './../routes/_works-pace/reports'
import { Route as ProjectsRouteImport } from './../routes/_works-pace/projects'
import { Route as OrganizationsRouteImport } from './../routes/_works-pace/organizations'
import { Route as LabelsRouteImport } from './../routes/_works-pace/labels'
import { Route as DashboardRouteImport } from './../routes/_works-pace/dashboard'
import { Route as ContactRouteImport } from './../routes/_landing/contact'
import { Route as AboutRouteImport } from './../routes/_landing/about'
import { Route as VerifyEmailRouteImport } from './../routes/_auth/verify-email'
import { Route as SignUpRouteImport } from './../routes/_auth/sign-up'
import { Route as SignInRouteImport } from './../routes/_auth/sign-in'
import { Route as ResetPasswordRouteImport } from './../routes/_auth/reset-password'
import { Route as ForgotPasswordRouteImport } from './../routes/_auth/forgot-password'
import { Route as TasksDottaskIdRouteImport } from './../routes/_works-pace/tasks.$taskId'
import { Route as SettingsDotprofileRouteImport } from './../routes/_works-pace/settings.profile'
import { Route as ProjectsDotprojectIdRouteImport } from './../routes/_works-pace/projects.$projectId'
import { Route as OrganizationsDotorganizationIdRouteImport } from './../routes/_works-pace/organizations.$organizationId'

const layoutsWorkspaceRoute = layoutsWorkspaceRouteImport.update({
  id: '/_workspace-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const layoutsLandingRoute = layoutsLandingRouteImport.update({
  id: '/_landing-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const layoutsAuthRoute = layoutsAuthRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutsLandingRoute,
} as any)
const appApiDotsplatRoute = appApiDotsplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => layoutsWorkspaceRoute,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => layoutsWorkspaceRoute,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => layoutsWorkspaceRoute,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => layoutsWorkspaceRoute,
} as any)
const LabelsRoute = LabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => layoutsWorkspaceRoute,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => layoutsWorkspaceRoute,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => layoutsLandingRoute,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => layoutsLandingRoute,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => layoutsAuthRoute,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => layoutsAuthRoute,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => layoutsAuthRoute,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => layoutsAuthRoute,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => layoutsAuthRoute,
} as any)
const TasksDottaskIdRoute = TasksDottaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const SettingsDotprofileRoute = SettingsDotprofileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => layoutsWorkspaceRoute,
} as any)
const ProjectsDotprojectIdRoute = ProjectsDotprojectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const OrganizationsDotorganizationIdRoute =
  OrganizationsDotorganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => OrganizationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/labels': typeof LabelsRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/api/$': typeof appApiDotsplatRoute
  '/organizations/$organizationId': typeof OrganizationsDotorganizationIdRoute
  '/projects/$projectId': typeof ProjectsDotprojectIdRoute
  '/settings/profile': typeof SettingsDotprofileRoute
  '/tasks/$taskId': typeof TasksDottaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/labels': typeof LabelsRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/api/$': typeof appApiDotsplatRoute
  '/organizations/$organizationId': typeof OrganizationsDotorganizationIdRoute
  '/projects/$projectId': typeof ProjectsDotprojectIdRoute
  '/settings/profile': typeof SettingsDotprofileRoute
  '/tasks/$taskId': typeof TasksDottaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth-layout': typeof layoutsAuthRouteWithChildren
  '/_landing-layout': typeof layoutsLandingRouteWithChildren
  '/_workspace-layout': typeof layoutsWorkspaceRouteWithChildren
  '/_auth-layout/forgot-password': typeof ForgotPasswordRoute
  '/_auth-layout/reset-password': typeof ResetPasswordRoute
  '/_auth-layout/sign-in': typeof SignInRoute
  '/_auth-layout/sign-up': typeof SignUpRoute
  '/_auth-layout/verify-email': typeof VerifyEmailRoute
  '/_landing-layout/about': typeof AboutRoute
  '/_landing-layout/contact': typeof ContactRoute
  '/_workspace-layout/dashboard': typeof DashboardRoute
  '/_workspace-layout/labels': typeof LabelsRoute
  '/_workspace-layout/organizations': typeof OrganizationsRouteWithChildren
  '/_workspace-layout/projects': typeof ProjectsRouteWithChildren
  '/_workspace-layout/reports': typeof ReportsRoute
  '/_workspace-layout/tasks': typeof TasksRouteWithChildren
  '/api/$': typeof appApiDotsplatRoute
  '/_landing-layout/': typeof IndexRoute
  '/_workspace-layout/organizations/$organizationId': typeof OrganizationsDotorganizationIdRoute
  '/_workspace-layout/projects/$projectId': typeof ProjectsDotprojectIdRoute
  '/_workspace-layout/settings/profile': typeof SettingsDotprofileRoute
  '/_workspace-layout/tasks/$taskId': typeof TasksDottaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/labels'
    | '/organizations'
    | '/projects'
    | '/reports'
    | '/tasks'
    | '/api/$'
    | '/organizations/$organizationId'
    | '/projects/$projectId'
    | '/settings/profile'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/labels'
    | '/organizations'
    | '/projects'
    | '/reports'
    | '/tasks'
    | '/api/$'
    | '/organizations/$organizationId'
    | '/projects/$projectId'
    | '/settings/profile'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/_auth-layout'
    | '/_landing-layout'
    | '/_workspace-layout'
    | '/_auth-layout/forgot-password'
    | '/_auth-layout/reset-password'
    | '/_auth-layout/sign-in'
    | '/_auth-layout/sign-up'
    | '/_auth-layout/verify-email'
    | '/_landing-layout/about'
    | '/_landing-layout/contact'
    | '/_workspace-layout/dashboard'
    | '/_workspace-layout/labels'
    | '/_workspace-layout/organizations'
    | '/_workspace-layout/projects'
    | '/_workspace-layout/reports'
    | '/_workspace-layout/tasks'
    | '/api/$'
    | '/_landing-layout/'
    | '/_workspace-layout/organizations/$organizationId'
    | '/_workspace-layout/projects/$projectId'
    | '/_workspace-layout/settings/profile'
    | '/_workspace-layout/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  layoutsAuthRoute: typeof layoutsAuthRouteWithChildren
  layoutsLandingRoute: typeof layoutsLandingRouteWithChildren
  layoutsWorkspaceRoute: typeof layoutsWorkspaceRouteWithChildren
  appApiDotsplatRoute: typeof appApiDotsplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace-layout': {
      id: '/_workspace-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof layoutsWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing-layout': {
      id: '/_landing-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof layoutsLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof layoutsAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing-layout/': {
      id: '/_landing-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof layoutsLandingRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof appApiDotsplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace-layout/tasks': {
      id: '/_workspace-layout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof layoutsWorkspaceRoute
    }
    '/_workspace-layout/reports': {
      id: '/_workspace-layout/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof layoutsWorkspaceRoute
    }
    '/_workspace-layout/projects': {
      id: '/_workspace-layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof layoutsWorkspaceRoute
    }
    '/_workspace-layout/organizations': {
      id: '/_workspace-layout/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof layoutsWorkspaceRoute
    }
    '/_workspace-layout/labels': {
      id: '/_workspace-layout/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof LabelsRouteImport
      parentRoute: typeof layoutsWorkspaceRoute
    }
    '/_workspace-layout/dashboard': {
      id: '/_workspace-layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof layoutsWorkspaceRoute
    }
    '/_landing-layout/contact': {
      id: '/_landing-layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof layoutsLandingRoute
    }
    '/_landing-layout/about': {
      id: '/_landing-layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof layoutsLandingRoute
    }
    '/_auth-layout/verify-email': {
      id: '/_auth-layout/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof layoutsAuthRoute
    }
    '/_auth-layout/sign-up': {
      id: '/_auth-layout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof layoutsAuthRoute
    }
    '/_auth-layout/sign-in': {
      id: '/_auth-layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof layoutsAuthRoute
    }
    '/_auth-layout/reset-password': {
      id: '/_auth-layout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof layoutsAuthRoute
    }
    '/_auth-layout/forgot-password': {
      id: '/_auth-layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof layoutsAuthRoute
    }
    '/_workspace-layout/tasks/$taskId': {
      id: '/_workspace-layout/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksDottaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/_workspace-layout/settings/profile': {
      id: '/_workspace-layout/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsDotprofileRouteImport
      parentRoute: typeof layoutsWorkspaceRoute
    }
    '/_workspace-layout/projects/$projectId': {
      id: '/_workspace-layout/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsDotprojectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/_workspace-layout/organizations/$organizationId': {
      id: '/_workspace-layout/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsDotorganizationIdRouteImport
      parentRoute: typeof OrganizationsRoute
    }
  }
}

interface layoutsAuthRouteChildren {
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

const layoutsAuthRouteChildren: layoutsAuthRouteChildren = {
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}

const layoutsAuthRouteWithChildren = layoutsAuthRoute._addFileChildren(
  layoutsAuthRouteChildren,
)

interface layoutsLandingRouteChildren {
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  IndexRoute: typeof IndexRoute
}

const layoutsLandingRouteChildren: layoutsLandingRouteChildren = {
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  IndexRoute: IndexRoute,
}

const layoutsLandingRouteWithChildren = layoutsLandingRoute._addFileChildren(
  layoutsLandingRouteChildren,
)

interface OrganizationsRouteChildren {
  OrganizationsDotorganizationIdRoute: typeof OrganizationsDotorganizationIdRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsDotorganizationIdRoute: OrganizationsDotorganizationIdRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsDotprojectIdRoute: typeof ProjectsDotprojectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsDotprojectIdRoute: ProjectsDotprojectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface TasksRouteChildren {
  TasksDottaskIdRoute: typeof TasksDottaskIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksDottaskIdRoute: TasksDottaskIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface layoutsWorkspaceRouteChildren {
  DashboardRoute: typeof DashboardRoute
  LabelsRoute: typeof LabelsRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  TasksRoute: typeof TasksRouteWithChildren
  SettingsDotprofileRoute: typeof SettingsDotprofileRoute
}

const layoutsWorkspaceRouteChildren: layoutsWorkspaceRouteChildren = {
  DashboardRoute: DashboardRoute,
  LabelsRoute: LabelsRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  TasksRoute: TasksRouteWithChildren,
  SettingsDotprofileRoute: SettingsDotprofileRoute,
}

const layoutsWorkspaceRouteWithChildren =
  layoutsWorkspaceRoute._addFileChildren(layoutsWorkspaceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  layoutsAuthRoute: layoutsAuthRouteWithChildren,
  layoutsLandingRoute: layoutsLandingRouteWithChildren,
  layoutsWorkspaceRoute: layoutsWorkspaceRouteWithChildren,
  appApiDotsplatRoute: appApiDotsplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
